name: 'octocov'
description: 'GitHub Action for octocov, a tool for collecting code coverage.'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  args:
    description: 'Arguments to pass to octocov'
    required: false
