name: 'Run octocov'
description: 'GitHub Action for octocov, a tool for collecting code coverage.'
branding:
  icon: 'octagon'
  color: 'gray-dark'
inputs:
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  version:
    description: Version of octocov
    default: latest
    required: false
  check-existence:
    description: Check for the existence of an existing octocov
    default: false
    required: false
  config:
    description: Config path
    required: false
  workdir:
    description: Working directory
    default: ''
    required: false
runs:
  using: 'composite'
  steps:
    -
      uses: k1LoW/gh-setup@v1
      with:
        repo: github.com/k1LoW/octocov
        github-token: ${{ inputs.github-token }}
        version: ${{ inputs.version }}
        bin-match: octocov
        strict: true
        force: ${{ !inputs.check-existence }}
    -
      name: Run octocov
      uses: actions/github-script@v7
      with:
        script: |
          const inputs = ${{ toJSON(inputs) }};
          const toolpath = await io.which('octocov', true)
          const opt = `--config=${inputs.config}`
          const options = {};
          options.cwd = inputs.workdir;
          await exec.exec(`${toolpath} ${opt}`, [], options)
      env:
        OCTOCOV_GITHUB_TOKEN: ${{ inputs.github-token }}

